"""Benchmark run configuration."""

from __future__ import annotations

import copy
import dataclasses
import ipaddress
import math
import pathlib
from dataclasses import dataclass, field

try:
    import yaml
except ImportError as exc:  # pragma: no cover - surfaced at CLI startup
    raise SystemExit("wan-bench needs PyYAML: pip install -e .") from exc


@dataclass
class WanConfig:
    """Emulated wide-area network applied by tc netem on every instance."""

    # Square RTT matrix in milliseconds. Node i uses region i % matrix size.
    rtt_csv: str = "latency/aws-10region-rtt.csv"
    jitter_ms: float = 0.0
    # Apply half the RTT to each direction.
    halve_rtt: bool = True
    # netem shapes host traffic; mimic enables the protocol's internal delay table.
    mode: str = "netem"
    # Per-peer netem queue depth in packets.
    netem_limit_pkts: int = 100_000


@dataclass
class FaultConfig:
    """A fault to inject during a `run`. `kind` selects the mechanism."""

    kind: str = "none"  # none | crash | ring | split | blip
    # Seconds after the metrics-active window opens (not after deploy).
    at_s: int = 40
    # Duration. split/blip: rules are cleared after for_s. crash: for_s > 0
    # restarts the killed containers in place after for_s; 0 keeps them down.
    for_s: int = 15
    nodes: list[int] = field(default_factory=list)  # crash: which validators
    pct: int = 10  # ring: percent of each node's out-edges to cut
    group_a: list[int] = field(default_factory=list)  # split: side A
    group_b: list[int] = field(default_factory=list)  # split: side B
    mode: str = "cut"  # blip/split: cut (tcp-reset) | drop (silent pause)


@dataclass
class RunConfig:
    # --- identity / cloud ---
    run_id: str = "run1"
    region: str = "eu-west-1"
    # The fleet always uses one AZ. None selects the first AZ with enough capacity.
    az: str | None = None
    profile: str | None = None  # AWS profile; None = default chain
    # Set a type explicitly, or use "" to select from the limits below.
    instance_type: str = "c5d.2xlarge"
    # Auto-selection constraints.
    min_vcpu: int = 8
    min_mem_gib: int = 16
    min_local_nvme: bool = True
    instance_families: list[str] = field(default_factory=lambda: ["c", "m"])
    max_type_candidates: int = 6
    ami: str | None = None  # None = latest Ubuntu 22.04 LTS (resolved via SSM)
    key_name: str = ""  # EC2 keypair name registered in `region`
    ssh_key_path: str = "~/.ssh/id_rsa"  # matching private key on this host
    ssh_user: str = "ubuntu"
    # None allows this host's public IP.
    ssh_open_cidr: str | None = None
    spot: bool = False  # request Spot instances (cheaper, interruptible)
    spot_max_price: str | None = None  # None = on-demand price cap (safe default)
    disk_gb: int = 50
    # Mount local instance storage at /opt/wanbench when available.
    use_instance_store: bool = True
    # Retaining monitoring is opt-in; normal teardown releases every resource.
    keep_monitoring_on_down: bool = False
    # Native dashboard JSON files to provision with the generic dashboard.
    dashboards: list[str] = field(default_factory=list)

    # --- topology ---
    # Vantage-family protocols share one image; Starfish uses a separate adapter.
    protocol: str = "vantage"
    nodes: int = 10
    # Registry reference or local image name for build-on-control.
    image: str = ""
    image_source: str = "registry"  # registry | build-on-control
    build_repo: str = ""  # build-on-control: local path to the protocol repo
    build_dockerfile: str = ""  # relative Dockerfile path within build_repo

    # --- workload ---
    rate: int = 200  # aggregate input tx/s across all nodes
    # Place counted useful load only on non-withholding authors. This keeps the
    # validity workload independent of Byzantine lane traffic.
    correct_load_only: bool = False
    # Aggregate uncounted payload generated by the withholding authors.
    adversarial_rate: int = 0
    tx_size: int = 512
    # random | all_zero; legacy all-zero is normalized during validation.
    tx_mode: str = "random"
    duration_s: int = 120
    # Extra entrypoint arguments, used by Starfish consensus selection.
    protocol_flags: list[str] = field(default_factory=list)
    # Broadcast Autobahn consensus votes instead of sending them to the leader.
    all_to_all: bool = False
    # Carry availability claims on AGB echoes instead of dedicated messages.
    echo_avail_claims: bool = True
    # Use one-byte committee identifiers on the Vantage primary wire.
    vantage_compact_ids: bool = True
    # Vantage sequence checkpoint recovery.
    sequence_checkpoints: bool = True
    sequence_install_enabled: bool = True
    sequence_checkpoint_interval_views: int = 20
    # Minimum cursor gap before checkpoint transfer.
    sequence_sync_min_gap_views: int = 50
    sequence_sync_chunk_outcomes: int = 256
    # Maximum outcome references per transfer chunk.
    sequence_sync_chunk_outcome_items: int = 1_600
    delta_ms: int = 200  # one-way delay bound; keep ~2x the WAN table's max one-way
    # Maximum wait before sealing a header.
    max_header_delay_ms: int = 100
    # Permanent original data-lane omission profile. Explicit entries are
    # validator indices and bind every publisher to one receiver cohort.
    data_lane_drop_publishers: list[int] = field(default_factory=list)
    data_lane_drop_receivers: list[int] = field(default_factory=list)
    # Alternatively select a prefix of the sorted committee and spread each
    # publisher's omissions using a coprime committee-index stride.
    data_lane_drop_staggered_senders: int = 0
    data_lane_drop_staggered_width: int = 0
    data_lane_drop_publisher_stride: int = 1
    data_lane_drop_staggered_stride: int = 1
    # Selected Byzantine publishers narrowcast but ignore later repair asks.
    data_lane_drop_silent_repair: bool = False
    # True drops original lane headers as well as worker batches. False keeps
    # metadata visible and isolates the heavy-payload repair burden.
    data_lane_drop_headers: bool = True
    # Selected Byzantine authors form one batch per Delta, retain the local
    # copy, and narrowcast their complete lane prefix only to a fixed
    # (f-1)-wide correct group. These f direct holders are one below PoA.
    # Groups are staggered across lanes so every correct consensus leader is
    # burdened. When selected as a leader, a Byzantine publisher uses its
    # certified cut so the experiment isolates honest-leader relay. Uniform
    # Byzantine load consumes resources but is reported separately from
    # honest-goodput and latency metrics.
    leader_relay_attack: bool = False

    # --- metrics-active window ---
    # Delay load until deployment and committee formation should be complete.
    spam_initial_delay_ms: int = 10_000
    # Scale the delay with committee size to cover launch fan-out.
    spam_delay_per_node_ms: int = 200
    # Submit before measurement to exclude the initial load step.
    spam_lead_ms: int = 25_000
    # Computed by deploy from one timestamp.
    client_activate_at_ms: int | None = None
    metrics_active_at_ms: int | None = None

    # --- orphan protection ---
    # Instances terminate if the orchestrator stops renewing this deadline. 0 disables it.
    deadman_minutes: int = 60

    # --- network + faults ---
    wan: WanConfig = field(default_factory=WanConfig)
    fault: FaultConfig = field(default_factory=FaultConfig)

    # --- metrics ---
    metrics_port: int = 6003  # vantage primary metrics; starfish derives one per node
    # None allows this host's public IP; "" keeps the port closed.
    grafana_open_cidr: str | None = None
    # Short intervals increase validator scrape overhead.
    prometheus_scrape_interval_s: int = 30

    @property
    def tags(self) -> dict[str, str]:
        return {"Project": "wan-bench", "Run": self.run_id, "Protocol": self.protocol}

    def spam_delay_budget_ms(self) -> int:
        """Return the deployment delay before clients submit."""
        return self.spam_initial_delay_ms + self.spam_delay_per_node_ms * self.nodes

    def permanently_unavailable_publisher_count(self) -> int:
        """Return authors whose counted payload cannot reach non-publishers.

        This is deliberately conservative.  Only an explicit fixed profile can
        establish that every non-publisher is omitted, and repair refusal makes
        that omission permanent.  Staggered profiles may leave different honest
        holders for every lane, so the harness does not infer a throughput ceiling
        for them.
        """
        publishers = set(self.data_lane_drop_publishers)
        receivers = set(self.data_lane_drop_receivers)
        if (not self.data_lane_drop_silent_repair or not publishers or
                publishers | receivers != set(range(self.nodes))):
            return 0
        return len(publishers)

    def reachable_rate(self) -> int:
        """Return counted offered tx/s that honest validators can materialize."""
        if self.correct_load_only:
            return self.rate
        if self.leader_relay_attack:
            publishers = (len(self.data_lane_drop_publishers)
                          if self.data_lane_drop_publishers
                          else self.data_lane_drop_staggered_senders)
            return self.rate * (self.nodes - publishers) // self.nodes
        available_authors = self.nodes - self.permanently_unavailable_publisher_count()
        # Validation makes rate exactly divisible by all load-bearing validators.
        return self.rate * available_authors // self.nodes

    def reachable_fraction(self) -> float:
        """Return the reachable share of the counted aggregate workload."""
        return self.reachable_rate() / self.rate

    def leader_relay_uncounted_rate(self) -> int:
        """Return the Byzantine share of a uniform leader-relay workload."""
        return self.rate - self.reachable_rate() if self.leader_relay_attack else 0

    @classmethod
    def from_dict(cls, data: dict) -> "RunConfig":
        raw = copy.deepcopy(data)
        wan = WanConfig(**(raw.pop("wan", {}) or {}))
        fault = FaultConfig(**(raw.pop("fault", {}) or {}))
        cfg = cls(**raw, wan=wan, fault=fault)
        cfg.validate()
        return cfg

    @classmethod
    def load(cls, path: str) -> "RunConfig":
        raw = yaml.safe_load(pathlib.Path(path).read_text()) or {}
        return cls.from_dict(raw)

    def validate(self) -> None:
        if not self.key_name:
            raise ValueError("config: key_name (EC2 keypair) is required")
        if not self.image:
            raise ValueError("config: image (GHCR node image) is required")
        if self.protocol not in ("vantage", "autobahn-seamless",
                                 "autobahn-optimistic", "simple-it",
                                 "simple-it-bracha", "starfish"):
            raise ValueError(f"config: unknown protocol {self.protocol!r}")
        if self.nodes < 1:
            raise ValueError("config: nodes must be >= 1")
        if self.protocol == "vantage" and self.vantage_compact_ids and self.nodes > 256:
            raise ValueError(
                "config: Vantage compact identifiers support at most 256 nodes")
        if type(self.rate) is not int or self.rate <= 0:
            raise ValueError("config: rate must be a positive integer")
        if type(self.adversarial_rate) is not int or self.adversarial_rate < 0:
            raise ValueError("config: adversarial_rate must be a non-negative integer")
        if type(self.correct_load_only) is not bool:
            raise ValueError("config: correct_load_only must be boolean")
        if type(self.all_to_all) is not bool:
            raise ValueError("config: all_to_all must be boolean")
        if self.tx_size < 1:
            raise ValueError("config: tx_size must be >= 1")
        self.tx_mode = self.tx_mode.replace("-", "_")  # legacy "all-zero" alias
        if self.tx_mode not in ("random", "all_zero"):
            raise ValueError(f"config: unknown tx_mode {self.tx_mode!r}")
        if self.duration_s < 1:
            raise ValueError("config: duration_s must be >= 1")
        if self.prometheus_scrape_interval_s < 1:
            raise ValueError("config: prometheus_scrape_interval_s must be >= 1")
        self._validate_ipv4_cidr("ssh_open_cidr", self.ssh_open_cidr)
        self._validate_ipv4_cidr(
            "grafana_open_cidr", self.grafana_open_cidr, allow_empty=True)
        if self.sequence_checkpoint_interval_views < 1:
            raise ValueError("config: sequence_checkpoint_interval_views must be >= 1")
        if self.sequence_sync_min_gap_views < 0:
            raise ValueError("config: sequence_sync_min_gap_views must be >= 0")
        if self.sequence_sync_chunk_outcomes < 1:
            raise ValueError("config: sequence_sync_chunk_outcomes must be >= 1")
        if self.sequence_sync_chunk_outcome_items < 1:
            raise ValueError("config: sequence_sync_chunk_outcome_items must be >= 1")
        publishers = self.data_lane_drop_publishers
        receivers = self.data_lane_drop_receivers
        staggered_senders = self.data_lane_drop_staggered_senders
        staggered_width = self.data_lane_drop_staggered_width
        staggered = staggered_senders > 0 or staggered_width > 0
        if bool(publishers) != bool(receivers):
            raise ValueError(
                "config: data-lane drop publishers and receivers must both be set")
        for name, values in (
            ("publishers", publishers),
            ("receivers", receivers),
        ):
            if any(type(index) is not int for index in values):
                raise ValueError(
                    f"config: data-lane drop {name} must be validator indices")
            if len(values) != len(set(values)):
                raise ValueError(
                    f"config: data-lane drop {name} contains duplicate indices")
            invalid = sorted(index for index in values
                             if index < 0 or index >= self.nodes)
            if invalid:
                raise ValueError(
                    f"config: data-lane drop {name} indices out of range: {invalid}")
        if set(publishers) & set(receivers):
            raise ValueError(
                "config: data-lane drop publishers and receivers must be disjoint")
        if publishers and staggered:
            raise ValueError(
                "config: explicit and staggered data-lane drop profiles are mutually exclusive")
        if type(staggered_senders) is not int or type(staggered_width) is not int:
            raise ValueError(
                "config: staggered data-lane sender count and width must be integers")
        if bool(staggered_senders) != bool(staggered_width):
            raise ValueError(
                "config: staggered data-lane sender count and width must both be set")
        if not 0 <= staggered_senders <= self.nodes:
            raise ValueError(
                "config: staggered data-lane sender count must be between 0 and nodes")
        if not 0 <= staggered_width < self.nodes:
            raise ValueError(
                "config: staggered data-lane width must be between 0 and nodes - 1")
        if (type(self.data_lane_drop_staggered_stride) is not int or
                self.data_lane_drop_staggered_stride < 1):
            raise ValueError("config: staggered data-lane stride must be positive")
        if (type(self.data_lane_drop_publisher_stride) is not int or
                self.data_lane_drop_publisher_stride < 1):
            raise ValueError("config: data-lane publisher stride must be positive")
        if (staggered and math.gcd(
                self.data_lane_drop_publisher_stride, self.nodes) != 1):
            raise ValueError(
                "config: data-lane publisher stride must be coprime with nodes")
        if (staggered and math.gcd(
                self.data_lane_drop_staggered_stride, self.nodes) != 1):
            raise ValueError(
                "config: staggered data-lane stride must be coprime with nodes")
        has_data_lane_drop = bool(publishers) or staggered
        publisher_count = len(publishers) if publishers else staggered_senders
        if (self.correct_load_only or self.adversarial_rate > 0) and not has_data_lane_drop:
            raise ValueError(
                "config: correct-only or adversarial load requires a data-lane drop profile")
        useful_nodes = self.nodes - publisher_count if self.correct_load_only else self.nodes
        if useful_nodes <= 0:
            raise ValueError("config: correct_load_only requires at least one correct author")
        if self.rate < useful_nodes or self.rate % useful_nodes:
            raise ValueError(
                f"config: useful rate must be >= and divisible by its {useful_nodes} "
                "load-bearing validators")
        if self.adversarial_rate and self.adversarial_rate % publisher_count:
            raise ValueError(
                f"config: adversarial_rate must be divisible by its {publisher_count} "
                "withholding publishers")
        if has_data_lane_drop and self.protocol == "starfish":
            raise ValueError(
                "config: data-lane drop is supported only by Vantage-binary protocols")
        if type(self.data_lane_drop_headers) is not bool:
            raise ValueError("config: data_lane_drop_headers must be boolean")
        if type(self.data_lane_drop_silent_repair) is not bool:
            raise ValueError("config: data_lane_drop_silent_repair must be boolean")
        if self.data_lane_drop_silent_repair and not has_data_lane_drop:
            raise ValueError(
                "config: silent data-lane repair requires a data-lane drop profile")
        if type(self.leader_relay_attack) is not bool:
            raise ValueError("config: leader_relay_attack must be boolean")
        if self.leader_relay_attack:
            fault_budget = (self.nodes - 1) // 3
            if not staggered or staggered_senders != fault_budget:
                raise ValueError(
                    "config: leader_relay_attack requires the maximal staggered "
                    "Byzantine publisher set")
            if staggered_width != self.nodes - 1:
                raise ValueError(
                    "config: leader_relay_attack must withhold from every non-author")
            if self.data_lane_drop_headers:
                raise ValueError(
                    "config: leader_relay_attack must keep lane headers visible")
            if not self.data_lane_drop_silent_repair:
                raise ValueError(
                    "config: leader_relay_attack requires Byzantine repair refusal")
            if self.correct_load_only or self.adversarial_rate:
                raise ValueError(
                    "config: leader_relay_attack uses one uniform total workload; "
                    "disable correct_load_only and adversarial_rate")
            if self.protocol == "autobahn-optimistic" and not self.all_to_all:
                raise ValueError(
                    "config: optimistic leader-relay requires Autobahn all-to-all")
        if self.protocol == "vantage" and self.metrics_port != 6003:
            raise ValueError("config: vantage primary metrics_port is fixed at 6003")
        if self.protocol == "starfish" and self.nodes < 4:
            raise ValueError("config: starfish benchmark-genesis needs at least 4 nodes")
        if self.protocol == "starfish" and self.tx_size <= 16:
            raise ValueError("config: starfish tx_size must be > 16 bytes")
        if self.protocol == "starfish":
            self._validate_starfish_consensus()
        if self.image_source not in ("registry", "build-on-control"):
            raise ValueError(f"config: unknown image_source {self.image_source!r}")
        if self.image_source == "build-on-control" and not self.build_repo:
            raise ValueError("config: build-on-control needs build_repo")
        if self.wan.mode not in ("netem", "mimic"):
            raise ValueError(f"config: unknown wan.mode {self.wan.mode!r}")
        if self.wan.mode == "mimic":
            if self.wan.rtt_csv != WanConfig().rtt_csv:
                raise ValueError(
                    "config: mimic mode uses the protocol's built-in AWS RTT table; "
                    "custom wan.rtt_csv requires netem mode")
            if self.wan.jitter_ms or not self.wan.halve_rtt:
                raise ValueError(
                    "config: mimic mode supports fixed RTT/2 latency only; jitter and "
                    "halve_rtt=false require netem mode")
        f = self.fault
        if f.kind not in ("none", "crash", "ring", "split", "blip"):
            raise ValueError(f"config: unknown fault kind {f.kind!r}")
        if f.kind == "crash" and not f.nodes:
            raise ValueError("config: crash fault needs fault.nodes")
        if f.kind == "crash" and len(set(f.nodes)) >= self.nodes:
            raise ValueError("config: crash fault must leave at least one node up")
        if f.kind == "split" and not (f.group_a and f.group_b):
            raise ValueError("config: split fault needs group_a and group_b")
        if f.mode not in ("cut", "drop"):
            raise ValueError(f"config: fault.mode must be cut or drop, got {f.mode!r}")
        if not 1 <= f.pct <= 100:
            raise ValueError("config: fault.pct must be between 1 and 100")
        indices = [*f.nodes, *f.group_a, *f.group_b]
        invalid = sorted({i for i in indices if i < 0 or i >= self.nodes})
        if invalid:
            raise ValueError(f"config: fault node indices out of range: {invalid}")
        if set(f.group_a) & set(f.group_b):
            raise ValueError("config: split fault groups must be disjoint")
        if f.at_s < 0 or f.for_s < 0:
            raise ValueError("config: fault.at_s and fault.for_s must be >= 0")
        if f.kind == "crash" and f.for_s > 0 and f.at_s + f.for_s + 30 > self.duration_s:
            raise ValueError(
                "config: the crash-restart cycle must fit the measured window: "
                "fault.at_s + fault.for_s + 30 <= duration_s")

    @staticmethod
    def _validate_ipv4_cidr(name: str, value: str | None,
                            allow_empty: bool = False) -> None:
        if value is None or (allow_empty and value == ""):
            return
        if value == "":
            raise ValueError(f"config: {name} cannot be empty")
        try:
            network = ipaddress.ip_network(value, strict=False)
        except ValueError as exc:
            raise ValueError(f"config: invalid {name} {value!r}") from exc
        if network.version != 4:
            raise ValueError(f"config: {name} must be an IPv4 CIDR")

    # Values accepted by Starfish's --consensus option.
    STARFISH_CONSENSUS = frozenset({
        "mysticeti", "mysticeti-bls", "mysticeti-l",
        "cordial-miners",
        "starfish", "starfish-bls", "starfish-l", "starfish-speed", "starfish-s",
        "sparse-starfish-speed", "sparse-starfish", "ssfs",
        "sailfish++", "sailfish-pp",
        "bluestreak",
    })

    def _validate_starfish_consensus(self) -> None:
        """Reject missing or unsupported Starfish consensus names."""
        flags = self.protocol_flags
        if "--consensus" not in flags:
            raise ValueError(
                "config: starfish requires an explicit protocol_flags "
                "['--consensus', <name>]; omitting it silently runs plain starfish "
                f"(clap default), one of: {sorted(self.STARFISH_CONSENSUS)}")
        i = flags.index("--consensus")
        if i + 1 >= len(flags):
            raise ValueError("config: protocol_flags '--consensus' has no value")
        name = flags[i + 1]
        if name not in self.STARFISH_CONSENSUS:
            raise ValueError(
                f"config: unknown starfish consensus {name!r} -- the binary would "
                f"silently fall back to plain starfish. Known: "
                f"{sorted(self.STARFISH_CONSENSUS)}")

    def dumps(self) -> str:
        return yaml.safe_dump(dataclasses.asdict(self), sort_keys=False)
